### ISSUE TITLE
add list of all teams in community.md

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#6]
I think page should be created programmatically, by querying the Zoltar API for the project info. Ideally, we could recreate this page occasionally (or on a regular basis, maybe using Travis?) to update the data for all teams. For starters, only teams that have submitted a forecast in the last 14 days should be included.

Each team's "card" will have the following information:
 - the title of each section should be the team name
 - the content of the card should have the number of submissions from the model from the team that has the highest number of submissions and the date of the most recent submission.
 - one link at the bottom should be the team website link provided in Zoltar (note that we have an issue to update these links to be the team links, not GitHub links)
 - a second link at the bottom should be a link to the Zoltar model page.

The teams should be sorted from most (at the top) to least (at the bottom) number of submissions.

So, one team's section of the `community.md` file would look like this:
```
      - title: [TEAM NAME FROM ZOLTAR HERE]
        content: >-
          The [MODEL NAME WITH THE MOST SUBMISSIONS] model has [XX] submitted forecasts. Most recent forecast was submitted on [DATE OF RECENT FORECAST].
        actions:
          - label: Website
            url: [MODEL LINK FROM ZOLTAR HERE]
            type: link
            new_window: true
          - label: Forecast data
            url: [LINK TO ZOLTAR MODEL PAGE]
            type: link
            new_window: true
```
